{
 "title": "stolon-cluster-monitoring",
 "tags": [
  "postgres",
  "stolon"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(stolon_cluster_identifier, cluster_name)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" },
   { "name": "host", "query": { "query": "label_values($host,instance)" } }
  ]
 },
 "panels": [
  { "title": "Cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Data Fetch Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stolon_proxy_get_cluster_info_errors and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Data Update Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stolon_proxy_update_proxy_info_errors and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership status",
   "type": "graph",
   "description": "Reports whether a sentinel is leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stolon_sentinel_is_leader and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"sentinel\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Time since last successful cluster check",
   "type": "graph",
   "description": "Tracks the time passed since the sentinel last successfully processed the sync loop. This implies that the sentinel was the leader.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() - stolon_sentinel_last_cluster_check_success_seconds and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"sentinel\"}) < 10000000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership changes",
   "type": "graph",
   "description": "Whether a sentinel instance has been elected leader",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(stolon_sentinel_leader_count[$interval]) and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"sentinel\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Stolon keepers and dbs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total keepers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stolon_cluster_identifier{component=\"proxy\",cluster_name=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Keeper Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "# Join metrics into a flat table of values per instance (instance, role, target_role, last_sync_success)\nmax by (instance, role) (\n  stolon_cluster_identifier{cluster_name=\"$cluster\"} * on (instance) group_left(role) (\n    time() - stolon_keeper_last_sync_success_seconds * on(instance) group_left(role) (\n      (stolon_keeper_local_role == 1) * on(instance) group_left(role) (\n        label_replace(stolon_keeper_target_role == 1, \"target_role\", \"$1\", \"role\", \"(.*)\")\n      )\n    )\n  )\n)"
    },
    {
     "expr": "max by (instance) (\n  time() - process_start_time_seconds and (stolon_keeper_shutdown_seconds and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"})\n)"
    },
    {
     "expr": "max by (instance) (\n  stolon_keeper_local_role and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"}\n)"
    }
   ]
  },
  {
   "title": "Time since last successful sync",
   "type": "timeseries",
   "description": "Tracks the time passed since the last PgBouncer reload. We expect stolon-pgbouncer to periodically reload PgBouncer, so this has exceeded the store poll interval then we know PgBouncer reloading is failing.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - ((stolon_keeper_last_sync_success_seconds > 0) and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "healthy DBs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(stolon_keeper_local_role and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"})  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy DBs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 33 },
   "targets": [
    {
     "expr": "sum(stolon_cluster_identifier{component=\"keeper\"}) - sum(stolon_keeper_local_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stolon_keeper_local_role{role=\"master\"} and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dbs cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(process_cpu_seconds_total[$__rate_interval]) and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dbs memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"keeper\"}) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Stolon proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Total Proxies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stolon_cluster_identifier{component=\"proxy\",cluster_name=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "max by (instance, role) (\n  stolon_cluster_identifier{cluster_name=\"$cluster\"} * on (instance) (\n    stolon_proxy_health\n  )\n)"
    }
   ]
  },
  {
   "title": "Healthy proxies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stolon_proxy_health and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"})  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Proxies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"}) - sum(stolon_proxy_health and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxies cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(process_cpu_seconds_total[$__rate_interval]) and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proxies memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes and on(instance) stolon_cluster_identifier{cluster_name=\"$cluster\", component=\"proxy\"}) / 1024 / 1024 ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}